services:
  - type: web
    name: ironrights-licensing-engine
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: YOUR_MONGO_CONNECTION_STRING
    pythonVersion: 3.10
    plan: free
    region: oregon  # You can change this if needed
